version: "3.3"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=framework

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=mongodb
    volumes:
      - ./data:/data/db

networks:
  default:
    external:
      name: nodejs_framework

